"""Add user_id to doctor

Revision ID: 93552162046e
Revises: 
Create Date: 2026-05-18 12:00:02.205369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93552162046e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tratamiento')
    op.drop_table('paciente')
    with op.batch_alter_table('ab_view_menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('ab_view_menu')
    with op.batch_alter_table('ab_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('ab_role')
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_doctor_fecha_hora'))

    op.drop_table('cita')
    with op.batch_alter_table('ab_permission_view_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_permission_view_id'))
        batch_op.drop_index(batch_op.f('idx_role_id'))
        batch_op.drop_index(batch_op.f('permission_view_id'))

    op.drop_table('ab_permission_view_role')
    with op.batch_alter_table('ab_user_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_id'))

    op.drop_table('ab_user_role')
    with op.batch_alter_table('ab_permission_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_permission_id'))
        batch_op.drop_index(batch_op.f('idx_view_menu_id'))
        batch_op.drop_index(batch_op.f('permission_id'))

    op.drop_table('ab_permission_view')
    with op.batch_alter_table('ab_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('ab_group')
    with op.batch_alter_table('ab_user_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_group_id'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.drop_index(batch_op.f('user_id'))

    op.drop_table('ab_user_group')
    with op.batch_alter_table('ab_register_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('ab_register_user')
    with op.batch_alter_table('ab_api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_api_key_lookup_hash'))
        batch_op.drop_index(batch_op.f('idx_api_key_prefix'))
        batch_op.drop_index(batch_op.f('idx_api_key_user_id'))
        batch_op.drop_index(batch_op.f('lookup_hash'))
        batch_op.drop_index(batch_op.f('uuid'))

    op.drop_table('ab_api_key')
    with op.batch_alter_table('ab_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('ab_user')
    with op.batch_alter_table('ab_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('ab_permission')
    op.drop_table('doctor')
    with op.batch_alter_table('ab_group_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('group_id'))
        batch_op.drop_index(batch_op.f('idx_group_id'))
        batch_op.drop_index(batch_op.f('idx_group_role_id'))

    op.drop_table('ab_group_role')
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('cita_id'))

    op.drop_table('pago')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('monto', mysql.FLOAT(), nullable=False),
    sa.Column('metodo_pago', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('observacion', mysql.TEXT(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('creado_en', mysql.DATETIME(), nullable=False),
    sa.Column('actualizado_en', mysql.DATETIME(), nullable=False),
    sa.Column('cita_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], name=op.f('pago_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('cita_id'), ['cita_id'], unique=True)

    op.create_table('ab_group_role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ab_group.id'], name=op.f('ab_group_role_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name=op.f('ab_group_role_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_group_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_group_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('group_id'), ['group_id', 'role_id'], unique=True)

    op.create_table('doctor',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_completo', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('especialidad', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('imagen', mysql.TEXT(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('creado_en', mysql.DATETIME(), nullable=True),
    sa.Column('actualizado_en', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ab_permission',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('ab_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=320), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('login_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fail_login_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('changed_on', mysql.DATETIME(), nullable=True),
    sa.Column('created_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], name=op.f('ab_user_ibfk_2')),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], name=op.f('ab_user_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('ab_api_key',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('key_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('lookup_hash', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('key_prefix', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('scopes', mysql.TEXT(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('expires_on', mysql.DATETIME(), nullable=True),
    sa.Column('revoked_on', mysql.DATETIME(), nullable=True),
    sa.Column('last_used_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name=op.f('ab_api_key_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uuid'), ['uuid'], unique=True)
        batch_op.create_index(batch_op.f('lookup_hash'), ['lookup_hash'], unique=True)
        batch_op.create_index(batch_op.f('idx_api_key_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_api_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('idx_api_key_lookup_hash'), ['lookup_hash'], unique=True)

    op.create_table('ab_register_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=320), nullable=False),
    sa.Column('registration_date', mysql.DATETIME(), nullable=True),
    sa.Column('registration_hash', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_register_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('ab_user_group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ab_group.id'], name=op.f('ab_user_group_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name=op.f('ab_user_group_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_user_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_id'), ['user_id', 'group_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_group_id'), ['group_id'], unique=False)

    op.create_table('ab_group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('ab_permission_view',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('view_menu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['ab_permission.id'], name=op.f('ab_permission_view_ibfk_1')),
    sa.ForeignKeyConstraint(['view_menu_id'], ['ab_view_menu.id'], name=op.f('ab_permission_view_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_permission_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('permission_id'), ['permission_id', 'view_menu_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_view_menu_id'), ['view_menu_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_permission_id'), ['permission_id'], unique=False)

    op.create_table('ab_user_role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name=op.f('ab_user_role_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name=op.f('ab_user_role_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_user_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_id'), ['user_id', 'role_id'], unique=True)

    op.create_table('ab_permission_view_role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_view_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_view_id'], ['ab_permission_view.id'], name=op.f('ab_permission_view_role_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name=op.f('ab_permission_view_role_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_permission_view_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('permission_view_id'), ['permission_view_id', 'role_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_permission_view_id'), ['permission_view_id'], unique=False)

    op.create_table('cita',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('hora', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('observacion', mysql.TEXT(), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('creado_en', mysql.DATETIME(), nullable=False),
    sa.Column('actualizado_en', mysql.DATETIME(), nullable=False),
    sa.Column('paciente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tratamiento_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('cita_ibfk_2')),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('cita_ibfk_1')),
    sa.ForeignKeyConstraint(['tratamiento_id'], ['tratamiento.id'], name=op.f('cita_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_doctor_fecha_hora'), ['doctor_id', 'fecha', 'hora'], unique=True)

    op.create_table('ab_role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('ab_view_menu',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ab_view_menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('paciente',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_completo', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('ci', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('edad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('creado_en', mysql.DATETIME(), nullable=False),
    sa.Column('actualizado_en', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tratamiento',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('precio', mysql.FLOAT(), nullable=True),
    sa.Column('duracion_minutos', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('creado_en', mysql.DATETIME(), nullable=True),
    sa.Column('actualizado_en', mysql.DATETIME(), nullable=True),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('tratamiento_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
